# /kubernetes-manifests/application/ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-demo-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: app.diploma.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-demo-app-service
            port:
              number: 80
